// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bootswatch.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class FormInput
{
	private final IMendixObject formInputMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "Bootswatch.FormInput";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Email("Email"),
		Password("Password"),
		TextArea("TextArea"),
		Radios("Radios"),
		Selects("Selects"),
		FocusedInput("FocusedInput"),
		DisabledInput("DisabledInput"),
		InputWarning("InputWarning"),
		InputError("InputError"),
		InputSuccess("InputSuccess"),
		LargeInput("LargeInput"),
		DefaultInput("DefaultInput"),
		SmallInput("SmallInput"),
		InputAddons("InputAddons"),
		Checkbox("Checkbox"),
		PanelHeader("PanelHeader"),
		PanelContent("PanelContent"),
		PanelFooter("PanelFooter"),
		Date("Date");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public FormInput(IContext context)
	{
		this(context, Core.instantiate(context, "Bootswatch.FormInput"));
	}

	protected FormInput(IContext context, IMendixObject formInputMendixObject)
	{
		if (formInputMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("Bootswatch.FormInput", formInputMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a Bootswatch.FormInput");

		this.formInputMendixObject = formInputMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'FormInput.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static bootswatch.proxies.FormInput initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return bootswatch.proxies.FormInput.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static bootswatch.proxies.FormInput initialize(IContext context, IMendixObject mendixObject)
	{
		return new bootswatch.proxies.FormInput(context, mendixObject);
	}

	public static bootswatch.proxies.FormInput load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return bootswatch.proxies.FormInput.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Email
	 */
	public final String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final String getEmail(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(IContext context, String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Password
	 */
	public final String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final String getPassword(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(IContext context, String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of TextArea
	 */
	public final String getTextArea()
	{
		return getTextArea(getContext());
	}

	/**
	 * @param context
	 * @return value of TextArea
	 */
	public final String getTextArea(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.TextArea.toString());
	}

	/**
	 * Set value of TextArea
	 * @param textarea
	 */
	public final void setTextArea(String textarea)
	{
		setTextArea(getContext(), textarea);
	}

	/**
	 * Set value of TextArea
	 * @param context
	 * @param textarea
	 */
	public final void setTextArea(IContext context, String textarea)
	{
		getMendixObject().setValue(context, MemberNames.TextArea.toString(), textarea);
	}

	/**
	 * Set value of Radios
	 * @param radios
	 */
	public final bootswatch.proxies.Options getRadios()
	{
		return getRadios(getContext());
	}

	/**
	 * @param context
	 * @return value of Radios
	 */
	public final bootswatch.proxies.Options getRadios(IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Radios.toString());
		if (obj == null)
			return null;

		return bootswatch.proxies.Options.valueOf((String) obj);
	}

	/**
	 * Set value of Radios
	 * @param radios
	 */
	public final void setRadios(bootswatch.proxies.Options radios)
	{
		setRadios(getContext(), radios);
	}

	/**
	 * Set value of Radios
	 * @param context
	 * @param radios
	 */
	public final void setRadios(IContext context, bootswatch.proxies.Options radios)
	{
		if (radios != null)
			getMendixObject().setValue(context, MemberNames.Radios.toString(), radios.toString());
		else
			getMendixObject().setValue(context, MemberNames.Radios.toString(), null);
	}

	/**
	 * Set value of Selects
	 * @param selects
	 */
	public final bootswatch.proxies.Selects getSelects()
	{
		return getSelects(getContext());
	}

	/**
	 * @param context
	 * @return value of Selects
	 */
	public final bootswatch.proxies.Selects getSelects(IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Selects.toString());
		if (obj == null)
			return null;

		return bootswatch.proxies.Selects.valueOf((String) obj);
	}

	/**
	 * Set value of Selects
	 * @param selects
	 */
	public final void setSelects(bootswatch.proxies.Selects selects)
	{
		setSelects(getContext(), selects);
	}

	/**
	 * Set value of Selects
	 * @param context
	 * @param selects
	 */
	public final void setSelects(IContext context, bootswatch.proxies.Selects selects)
	{
		if (selects != null)
			getMendixObject().setValue(context, MemberNames.Selects.toString(), selects.toString());
		else
			getMendixObject().setValue(context, MemberNames.Selects.toString(), null);
	}

	/**
	 * @return value of FocusedInput
	 */
	public final String getFocusedInput()
	{
		return getFocusedInput(getContext());
	}

	/**
	 * @param context
	 * @return value of FocusedInput
	 */
	public final String getFocusedInput(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.FocusedInput.toString());
	}

	/**
	 * Set value of FocusedInput
	 * @param focusedinput
	 */
	public final void setFocusedInput(String focusedinput)
	{
		setFocusedInput(getContext(), focusedinput);
	}

	/**
	 * Set value of FocusedInput
	 * @param context
	 * @param focusedinput
	 */
	public final void setFocusedInput(IContext context, String focusedinput)
	{
		getMendixObject().setValue(context, MemberNames.FocusedInput.toString(), focusedinput);
	}

	/**
	 * @return value of DisabledInput
	 */
	public final String getDisabledInput()
	{
		return getDisabledInput(getContext());
	}

	/**
	 * @param context
	 * @return value of DisabledInput
	 */
	public final String getDisabledInput(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.DisabledInput.toString());
	}

	/**
	 * Set value of DisabledInput
	 * @param disabledinput
	 */
	public final void setDisabledInput(String disabledinput)
	{
		setDisabledInput(getContext(), disabledinput);
	}

	/**
	 * Set value of DisabledInput
	 * @param context
	 * @param disabledinput
	 */
	public final void setDisabledInput(IContext context, String disabledinput)
	{
		getMendixObject().setValue(context, MemberNames.DisabledInput.toString(), disabledinput);
	}

	/**
	 * @return value of InputWarning
	 */
	public final String getInputWarning()
	{
		return getInputWarning(getContext());
	}

	/**
	 * @param context
	 * @return value of InputWarning
	 */
	public final String getInputWarning(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.InputWarning.toString());
	}

	/**
	 * Set value of InputWarning
	 * @param inputwarning
	 */
	public final void setInputWarning(String inputwarning)
	{
		setInputWarning(getContext(), inputwarning);
	}

	/**
	 * Set value of InputWarning
	 * @param context
	 * @param inputwarning
	 */
	public final void setInputWarning(IContext context, String inputwarning)
	{
		getMendixObject().setValue(context, MemberNames.InputWarning.toString(), inputwarning);
	}

	/**
	 * @return value of InputError
	 */
	public final String getInputError()
	{
		return getInputError(getContext());
	}

	/**
	 * @param context
	 * @return value of InputError
	 */
	public final String getInputError(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.InputError.toString());
	}

	/**
	 * Set value of InputError
	 * @param inputerror
	 */
	public final void setInputError(String inputerror)
	{
		setInputError(getContext(), inputerror);
	}

	/**
	 * Set value of InputError
	 * @param context
	 * @param inputerror
	 */
	public final void setInputError(IContext context, String inputerror)
	{
		getMendixObject().setValue(context, MemberNames.InputError.toString(), inputerror);
	}

	/**
	 * @return value of InputSuccess
	 */
	public final String getInputSuccess()
	{
		return getInputSuccess(getContext());
	}

	/**
	 * @param context
	 * @return value of InputSuccess
	 */
	public final String getInputSuccess(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.InputSuccess.toString());
	}

	/**
	 * Set value of InputSuccess
	 * @param inputsuccess
	 */
	public final void setInputSuccess(String inputsuccess)
	{
		setInputSuccess(getContext(), inputsuccess);
	}

	/**
	 * Set value of InputSuccess
	 * @param context
	 * @param inputsuccess
	 */
	public final void setInputSuccess(IContext context, String inputsuccess)
	{
		getMendixObject().setValue(context, MemberNames.InputSuccess.toString(), inputsuccess);
	}

	/**
	 * @return value of LargeInput
	 */
	public final String getLargeInput()
	{
		return getLargeInput(getContext());
	}

	/**
	 * @param context
	 * @return value of LargeInput
	 */
	public final String getLargeInput(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.LargeInput.toString());
	}

	/**
	 * Set value of LargeInput
	 * @param largeinput
	 */
	public final void setLargeInput(String largeinput)
	{
		setLargeInput(getContext(), largeinput);
	}

	/**
	 * Set value of LargeInput
	 * @param context
	 * @param largeinput
	 */
	public final void setLargeInput(IContext context, String largeinput)
	{
		getMendixObject().setValue(context, MemberNames.LargeInput.toString(), largeinput);
	}

	/**
	 * @return value of DefaultInput
	 */
	public final String getDefaultInput()
	{
		return getDefaultInput(getContext());
	}

	/**
	 * @param context
	 * @return value of DefaultInput
	 */
	public final String getDefaultInput(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.DefaultInput.toString());
	}

	/**
	 * Set value of DefaultInput
	 * @param defaultinput
	 */
	public final void setDefaultInput(String defaultinput)
	{
		setDefaultInput(getContext(), defaultinput);
	}

	/**
	 * Set value of DefaultInput
	 * @param context
	 * @param defaultinput
	 */
	public final void setDefaultInput(IContext context, String defaultinput)
	{
		getMendixObject().setValue(context, MemberNames.DefaultInput.toString(), defaultinput);
	}

	/**
	 * @return value of SmallInput
	 */
	public final String getSmallInput()
	{
		return getSmallInput(getContext());
	}

	/**
	 * @param context
	 * @return value of SmallInput
	 */
	public final String getSmallInput(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.SmallInput.toString());
	}

	/**
	 * Set value of SmallInput
	 * @param smallinput
	 */
	public final void setSmallInput(String smallinput)
	{
		setSmallInput(getContext(), smallinput);
	}

	/**
	 * Set value of SmallInput
	 * @param context
	 * @param smallinput
	 */
	public final void setSmallInput(IContext context, String smallinput)
	{
		getMendixObject().setValue(context, MemberNames.SmallInput.toString(), smallinput);
	}

	/**
	 * @return value of InputAddons
	 */
	public final String getInputAddons()
	{
		return getInputAddons(getContext());
	}

	/**
	 * @param context
	 * @return value of InputAddons
	 */
	public final String getInputAddons(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.InputAddons.toString());
	}

	/**
	 * Set value of InputAddons
	 * @param inputaddons
	 */
	public final void setInputAddons(String inputaddons)
	{
		setInputAddons(getContext(), inputaddons);
	}

	/**
	 * Set value of InputAddons
	 * @param context
	 * @param inputaddons
	 */
	public final void setInputAddons(IContext context, String inputaddons)
	{
		getMendixObject().setValue(context, MemberNames.InputAddons.toString(), inputaddons);
	}

	/**
	 * @return value of Checkbox
	 */
	public final Boolean getCheckbox()
	{
		return getCheckbox(getContext());
	}

	/**
	 * @param context
	 * @return value of Checkbox
	 */
	public final Boolean getCheckbox(IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.Checkbox.toString());
	}

	/**
	 * Set value of Checkbox
	 * @param checkbox
	 */
	public final void setCheckbox(Boolean checkbox)
	{
		setCheckbox(getContext(), checkbox);
	}

	/**
	 * Set value of Checkbox
	 * @param context
	 * @param checkbox
	 */
	public final void setCheckbox(IContext context, Boolean checkbox)
	{
		getMendixObject().setValue(context, MemberNames.Checkbox.toString(), checkbox);
	}

	/**
	 * @return value of PanelHeader
	 */
	public final String getPanelHeader()
	{
		return getPanelHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of PanelHeader
	 */
	public final String getPanelHeader(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.PanelHeader.toString());
	}

	/**
	 * Set value of PanelHeader
	 * @param panelheader
	 */
	public final void setPanelHeader(String panelheader)
	{
		setPanelHeader(getContext(), panelheader);
	}

	/**
	 * Set value of PanelHeader
	 * @param context
	 * @param panelheader
	 */
	public final void setPanelHeader(IContext context, String panelheader)
	{
		getMendixObject().setValue(context, MemberNames.PanelHeader.toString(), panelheader);
	}

	/**
	 * @return value of PanelContent
	 */
	public final String getPanelContent()
	{
		return getPanelContent(getContext());
	}

	/**
	 * @param context
	 * @return value of PanelContent
	 */
	public final String getPanelContent(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.PanelContent.toString());
	}

	/**
	 * Set value of PanelContent
	 * @param panelcontent
	 */
	public final void setPanelContent(String panelcontent)
	{
		setPanelContent(getContext(), panelcontent);
	}

	/**
	 * Set value of PanelContent
	 * @param context
	 * @param panelcontent
	 */
	public final void setPanelContent(IContext context, String panelcontent)
	{
		getMendixObject().setValue(context, MemberNames.PanelContent.toString(), panelcontent);
	}

	/**
	 * @return value of PanelFooter
	 */
	public final String getPanelFooter()
	{
		return getPanelFooter(getContext());
	}

	/**
	 * @param context
	 * @return value of PanelFooter
	 */
	public final String getPanelFooter(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.PanelFooter.toString());
	}

	/**
	 * Set value of PanelFooter
	 * @param panelfooter
	 */
	public final void setPanelFooter(String panelfooter)
	{
		setPanelFooter(getContext(), panelfooter);
	}

	/**
	 * Set value of PanelFooter
	 * @param context
	 * @param panelfooter
	 */
	public final void setPanelFooter(IContext context, String panelfooter)
	{
		getMendixObject().setValue(context, MemberNames.PanelFooter.toString(), panelfooter);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return formInputMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final bootswatch.proxies.FormInput that = (bootswatch.proxies.FormInput) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "Bootswatch.FormInput";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
