// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bootswatch.proxies;

public enum Options
{
	Option_one_is_this(new String[][] { new String[] { "en_US", "Option one is this" } }),
	Option_two_can_be_something_else(new String[][] { new String[] { "en_US", "Option two can be something else" } });

	private java.util.Map<String,String> captions;

	private Options(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
