// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bootswatch.proxies;

public enum Options
{
	Option_one_is_this(new java.lang.String[][] { new java.lang.String[] { "en_US", "Option one is this" } }),
	Option_two_can_be_something_else(new java.lang.String[][] { new java.lang.String[] { "en_US", "Option two can be something else" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Options(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
