// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bootswatch.proxies;

public enum Selects
{
	_1(new String[][] { new String[] { "en_US", "1" } }),
	_2(new String[][] { new String[] { "en_US", "2" } }),
	_3(new String[][] { new String[] { "en_US", "3" } }),
	_4(new String[][] { new String[] { "en_US", "4" } }),
	_5(new String[][] { new String[] { "en_US", "5" } });

	private java.util.Map<String,String> captions;

	private Selects(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
